sudo: required
services:
  - docker
  
before_install:
  - docker build -t dido/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dido/docker-react npm run test 
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-1-1adjhsjd1"
  bucket_path:  "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"  
  