FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

COPY --chown=node:node ./package.json ./
RUN npm config set fetch-retry-mintimeout 20000;npm config set fetch-retry-maxtimeout 180000;npm install
COPY --chown=node:node ./ ./


CMD ["npm","start"]
